#!/usr/bin/env bash

rsync -avh --progress --delete --exclude '._*'  --exclude '.DS_Store'  --exclude '.fseventsd' --exclude '.Trashes' --exclude '.Spotlight-V100' /Volumes/Expansion/ /Volumes/WD\ Elements/
